template_instruction:
  - "论文封面书脊"
  - "四号黑体字"
  - "小四号黑体字"
  - "注：任务书应该附在已完成的毕业设计（论文）的首页"
  - "（题目）"
  - "论文题目"
template_sample_value:
  - "王小亮"
  - "黄欣"
  - "黄  欣"
  - "李兴新"
  - "38020326"
  - "TN953"
  - "电子信息工程学院"
  - "油/水电迁移微观动态过程的研究"
  - "油/水电迁移"
  - "Micro-process of Oil/Water Transferring in Electric Field"
  - "Electro-desalting is the most efficient"
  - "高频高压，油/水电迁移"
template_static_required:
  - "单位代码"
  - "学号"
  - "分类号"
  - "毕业设计(论文)"
  - "本人声明"
  - "我声明，本论文及其研究工作是由本人在导师指导下独立完成的"
  - "摘    要"
  - "摘 要"
  - "Abstract"
  - "Key Words"
  - "Key words"
  - "目       录"
  - "目 录"
  - "北京航空航天大学毕业设计(论文)"
  - "Author:"
  - "Author :"
  - "Tutor:"
  - "Tutor :"
  - "第 I 页"
  - "第 1 页"
user_fill_value:
  - "10006"
  - "17375303"
  - "TP273"
  - "基于实拍图像的光电系统性能评估关键技术研究"
  - "自动化科学与电气工程学院"
  - "自动化"
  - "崔润昊"
  - "唐荻音"
  - "2021 年 5 月"
  - "Research on Key Technologies of Performance Evaluation of Electro-Optical System Based on Actual Scene Images"
source_body_content:
  - "1 绪论"
  - "1.1 课题来源与背景"
  - "本课题来源于国家自然科学基金"
  - "机载光电探测系统"
source_frontmatter_content:
  - "中文摘要"
  - "中文关键词"
  - "英文摘要"
  - "Key Words"
  - "任务书"
